import { PostFilter } from "@/generated/graphql";
import clsx from "clsx";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { CSSTransition } from "react-transition-group";
import { PopularPostFeed } from "@/features/post/components/PopularPostFeed.component";
import { RecentPostFeed } from "@/features/post/components/RecentPostFeed.component";

const Home: NextPage = () => {
  const [tab, setTab] = useState<PostFilter>(PostFilter.Popularity);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Instagram <a>Ranked Feed</a>
        </h1>

        <div className="mt-8 mb-2 tabs tabs-boxed">
          <a
            className={clsx(
              "tab",
              tab === PostFilter.Popularity && "tab-active"
            )}
            onClick={() => setTab(PostFilter.Popularity)}
          >
            Popular Post
          </a>
          <a
            className={clsx("tab", tab === PostFilter.Recency && "tab-active")}
            onClick={() => setTab(PostFilter.Recency)}
          >
            Recent Post
          </a>
        </div>

        <div className="flex items-center justify-center flex-wrap max-w-[1000px]">
          <CSSTransition
            classNames="csstransition-menu--primary"
            in={tab === PostFilter.Popularity}
            unmountOnExit
            timeout={300}
          >
            <PopularPostFeed />
          </CSSTransition>
          <CSSTransition
            classNames="csstransition-menu--primary"
            in={tab === PostFilter.Recency}
            unmountOnExit
            timeout={300}
          >
            <RecentPostFeed />
          </CSSTransition>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
